### POST

POST http://localhost:4004/catalog/submitOrder
Content-Type: application/json

{
    "recipient": "yatsea@sap.com",
    "orderData": {
        "CustomerName": "yatsea",
        "CustomerEmail": "yatsea@sap.com",
        "Address": "590 St Kilda Rd, Melbourne VIC 3004, Australia",
        "ProductID": "1",
        "ProductName": "mouse",
        "Quantity": 1
    }
}

###

GET http://localhost:4004/catalog/getTaskDetails(user='Pick-up')
Content-Type: application/json

###

POST http://localhost:4004/catalog/completeTask
Content-Type: application/json

{
    "id"  : "9c63585a-daa8-11ec-8310-eeee0a85784b",
    "user" : "usertask3",
    "wfId" : "6e77f406-da95-11ec-8310-eeee0a85784b"
}
